# Solidity tests
sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
env:
  global:
    - SOLIDITY_COVERAGE=true
    - CONTINUOUS_INTEGRATION=false
before_script:
  - truffle version
script:
  - npm run test
